title: Anthng
author: "An Nguyen"
address: HCMC, VN"

description: "Hello I'm An"
baseurl: ""
url: "https://anthng.github.io/" 
github_username: anthng
encoding: UTF-8

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

markdown: kramdown
permalink: pretty
paginate: 4
paginate_path: "blogs/page:num/"

toc:
  ordered_list: true
